### ISSUE TITLE
fix traceToken bug

### ISSUE THREAD

**Issue by dpsoft** [neowulf33/kamon-tracetoken-bug#1]
@neowulf33 you only need change this 
```
   <property name="LOG_ENCODER_PATTERN"
              value="%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level %logger{36} %X{akkaTimestamp} [%traceToken] - %msg%n"
    />
```
to 

```
 <property name="LOG_ENCODER_PATTERN"
              value="%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level %logger{36} %X{akkaTimestamp} [%X{traceToken}] - %msg%n"
    />
```

in order to extract the `traceToken` from `MDC`

**Comment by neowulf** [comment]
Thank you @dpsoft. That's exactly what I have been able to do which works.

However, why is it that the MDC values not propagated to the trace context?

**Comment by dpsoft** [comment]
@neowulf33 I just make a PR.

**Comment by neowulf** [comment]
Thank you. But isn't this a bug in kamon?

**Comment by dpsoft** [comment]
@neowulf33 a bug? why?

**Comment by neowulf** [comment]
My understanding was using the conversion rule to access kamon's value is desirable.

This project demonstrates that the MDC values do not get propagated to the trace context when using logback's conversion rule. 

Is it recommended that the kamon values be accessed directly from MDC?

**Comment by dpsoft** [comment]
@neowulf33 you are right, you can use de conversion rule with kamon if you aren't using an `Async Appender` otherwise you need pass the data from the current thread to the AsyncAppender thread pool, so you need use some functionality as `MDC`, kamon by default pass to the `MDC` only the `TraceContext` `key` and `value`, but if you want add some extra information you can take a look to our doc about [mdc-in-an-asyncronous-environment](http://kamon.io/integrations/logback/mdc-in-an-asyncronous-environment/)

**Comment by neowulf** [comment]
I see, thank you!
